/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qr_scanner;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author skyma
 */
public class Horario extends javax.swing.JPanel {
    String ruta;
    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
    }
    public void actualizarImagen(String textoQR) {
        switch (textoQR) {
            case "horario1":
                // Asegúrate de reemplazar estas rutas con las rutas a tus imágenes
                ruta="./recursos/comunes/fotos/0.jpg";
                break;
            case "horario2":
                ruta="./recursos/comunes/fotos/0.jpg";
                break;
            // Agrega más casos según sea necesario
            default:
                //jLabel1.setIcon(new ImageIcon("./recursos/comunes/fotos/2.jpg"));
                ruta="./recursos/comunes/fotos/2.jpg";
                break;
        }
        this.revalidate(); // Actualiza el panel para mostrar cambios
        this.repaint();
    }
   public String getLabelIcon() {
    return ruta;
}   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
