/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.EnumMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * IMPORTANTE AL CAMBIAR DIMENSIONES EN DISEÑO HAY QUE ACTUALIZAR LOS
 * VALORES WIDTH Y HEIGHT
 */
public class Confirmacion_Pago extends javax.swing.JPanel {

    /**
     * Creates new form Confirmacion_Menu_Final
     */
    private Ventana padre;
    private String codigo;
    private String datos;
    
    int WIDTH = 600;
    int HEIGHT = 600;
    
    private static final String UTF_8 = "UTF-8";
    
    public Confirmacion_Pago(Ventana p) {
        initComponents();
        padre = p;
        codigo = "";
    }
    
    public Confirmacion_Pago(Ventana p, String d) {
        initComponents();
        padre = p;
        datos = d;
        codigo = "";
        
        generaQR(datos);
    }
    
    /*
    public void setCodigo(String c){
        this.codigo = c;
        txtfCodigo.setText(c);
    }*/
    
    private void generaQR(String datos){
        QRCodeWriter qr = new QRCodeWriter();
        
        int size = 1000;
        
        try {
            BitMatrix matrix = qr.encode(datos, BarcodeFormat.QR_CODE, size, size);
            File f = new File("./qr.png");
            
            int matrixTam = matrix.getWidth();
            
            BufferedImage image = new BufferedImage(matrixTam, matrixTam, BufferedImage.TYPE_INT_RGB);
            image.createGraphics();
            
            Graphics2D gd = (Graphics2D) image.getGraphics();
            gd.setColor(Color.WHITE);
            gd.fillRect(0, 0, size, size);
            gd.setColor(Color.BLACK);
            
            for(int b = 0; b < matrixTam; b++){
                for(int j = 0; j < matrixTam; j++){
                    if(matrix.get(b, j)){
                        gd.fillRect(b, j, 1, 1);
                    }
                }
            }
            
            ImageIO.write(image, "png", f);
            Image miQR = new ImageIcon("./qr.png").getImage();
            System.out.println(datos);
            ImageIcon icon = new ImageIcon(miQR.getScaledInstance(WIDTH, HEIGHT, 0));
            txtQR.setIcon(icon);
            
        } catch (WriterException ex) {
            Logger.getLogger(Confirmacion_Pago.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Confirmacion_Pago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo1 = new javax.swing.JLabel();
        boton_si = new javax.swing.JButton();
        jLabel_titulo2 = new javax.swing.JLabel();
        txtQR = new javax.swing.JLabel();

        setOpaque(false);

        jLabel_titulo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_titulo1.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo1.setText("Emitiendo NFC...");

        boton_si.setBackground(new java.awt.Color(255, 255, 255));
        boton_si.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        boton_si.setText("Volver al menú");
        boton_si.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        boton_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_siActionPerformed(evt);
            }
        });

        jLabel_titulo2.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel_titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo2.setText("Pago desde la App");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 245, Short.MAX_VALUE)
                        .addComponent(txtQR, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_titulo2)
                .addGap(366, 366, 366))
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(boton_si, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel_titulo2)
                .addGap(329, 329, 329)
                .addComponent(txtQR, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(195, 195, 195)
                .addComponent(jLabel_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_si, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_siActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_boton_siActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_si;
    private javax.swing.JLabel jLabel_titulo1;
    private javax.swing.JLabel jLabel_titulo2;
    private javax.swing.JLabel txtQR;
    // End of variables declaration//GEN-END:variables
}
