/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class Confirmacion_Menu_Final extends javax.swing.JPanel {

    /**
     * Creates new form Confirmacion_Menu_Final
     */
    private Ventana padre;
    
    public Confirmacion_Menu_Final(Ventana p) {
        initComponents();
        padre = p;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_titulo1 = new javax.swing.JLabel();
        boton_si = new javax.swing.JButton();
        boton_no = new javax.swing.JButton();

        setOpaque(false);

        jLabel_titulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("desea volver?");

        jLabel_titulo1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo1.setText("¿Está seguro de que");

        boton_si.setBackground(new java.awt.Color(255, 255, 255));
        boton_si.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        boton_si.setText("Sí");
        boton_si.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 4, true));
        boton_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_siActionPerformed(evt);
            }
        });

        boton_no.setBackground(new java.awt.Color(255, 255, 255));
        boton_no.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        boton_no.setText("No");
        boton_no.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 4, true));
        boton_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                    .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_si, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(297, 297, 297)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_si, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_no, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(258, 258, 258))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_siActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_boton_siActionPerformed

    private void boton_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_noActionPerformed
        padre.anterior();
    }//GEN-LAST:event_boton_noActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_no;
    private javax.swing.JButton boton_si;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_titulo1;
    // End of variables declaration//GEN-END:variables
}
