/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.HashMap;
import javax.swing.JComboBox;
import javax.swing.JTextArea;

/**
 *
 * @author 34611
 */
public class Localizacion_Profesorado extends javax.swing.JPanel {

    private Ventana padre;
    private HashMap<String, String> infoProfesores;
    
    //private JComboBox<String> comboBoxProfesores;
    //private JTextArea textAreaInfo;
    
    public Localizacion_Profesorado(Ventana p) {
        initComponents();
        padre = p;
        inicializarDatosProfesores();
        llenarComboBoxProfesores();
    }
    
    private void inicializarDatosProfesores() {
    infoProfesores = new HashMap<>();

    infoProfesores.put("Marcelino Cabrera Cuevas",
        "Tutorías:\n" +
        "         - Miércoles de 9:00 a 11:00\n" +
        "         - Viernes de 8:30 a 10:30 y de 12:20 a 14:30\n" +
        "Despacho: 25 planta 3 ETSIIT.");

    infoProfesores.put("Ramón López-Cózar Delgado",
        "Tutorías:\n" +
        "      - Martes de 10:30 a 13:30\n" +
        "      - Miércoles de 10:30 a 13:30\n" +
        "Despacho: 26 planta 3 ETSIIT.");

    infoProfesores.put("Jorge Revelles Moreno",
        "Tutorías:\n" +
        "      - Martes de 9:30 a 11:30\n" +
        "      - Miércoles de 9:30 a 11:30\n" +
        "      - Jueves de 10:30 a 12:30\n" +
        "Despacho: 4 planta 3 ETSIIT.");

    infoProfesores.put("Manuel Pegalajar Cuéllar",
        "Tutorías:\n" +
        "      - Lunes de 9:30 a 11:30\n" +
        "      - Martes de 9:30 a 11:30 y de 15:30 a 17:30\n" +
        "Despacho: 19 planta 4 ETSIIT.");

    infoProfesores.put("Pablo Mesejo",
        "Tutorías:\n" +
        "      - Martes y miércoles de 10:00 a 13:00\n" +
        "Despacho: 1.10 edificio auxiliar de la ETSIIT.");

    infoProfesores.put("Víctor Vargas Pérez",
        "Tutorías:\n" +
        "    - Jueves de 8:30 a 10:00\n" +
        "Despacho: IB-11 CITIC.");

    infoProfesores.put("Luis Miguel Campos Ibáñez",
        "Tutorías:\n" +
        "      - Lunes de 11:30 a 14:40\n" +
        "      - Martes de 11:30 a 14:30\n" +
        "Despacho: 10 planta 2 ETSIIT.");

    infoProfesores.put("Miguel García Silvente",
        "Tutorías:\n" +
        "      - Lunes de 9:30 a 11:30\n" +
        "      - Martes de 11:30 a 13:30\n" +
        "      - Miércoles de 11:00 a 13:00\n" +
        "Despacho: 30 planta 3 ETSIIT.");
}

    
    private void llenarComboBoxProfesores(){
        comboBoxProfesores.removeAllItems(); // Limpia todos los elementos existentes
        for (String profesor : infoProfesores.keySet()){
            comboBoxProfesores.addItem(profesor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxProfesores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaInfo = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Seleccione el nombre del");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setText("profesor del que quiera");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setText("obtener información");

        comboBoxProfesores.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboBoxProfesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxProfesores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 4, true));
        comboBoxProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProfesoresActionPerformed(evt);
            }
        });

        textAreaInfo.setColumns(20);
        textAreaInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textAreaInfo.setRows(5);
        jScrollPane1.setViewportView(textAreaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(comboBoxProfesores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 410, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(23, 23, 23)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)))
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(78, 78, 78)
                .addComponent(comboBoxProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(890, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProfesoresActionPerformed
        String profesorSeleccionado = (String) comboBoxProfesores.getSelectedItem();
        String info = infoProfesores.getOrDefault(profesorSeleccionado, "Información no disponible");
        textAreaInfo.setText(info);
    }//GEN-LAST:event_comboBoxProfesoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaInfo;
    // End of variables declaration//GEN-END:variables
}
