/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author 34611
 */

import javax.swing.JButton;
import javax.swing.JPanel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;


public class Menu_Botones_Generico extends javax.swing.JFrame {

    //private JPanel panel;

    public Menu_Botones_Generico(String[] nombresBotones) {
        initComponents();  // Llama primero al método initComponents generado por NetBeans
        myInitComponents(nombresBotones);  // Luego llama a tu método personalizado
    }

    
    private void myInitComponents(String[] nombresBotones) {
        JPanel panel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 50, 10, 50); // Ajusta esto según sea necesario

        // Configuración de GridBagConstraints para centrar los componentes y dar espacio extra
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.weightx = 1;
        gbc.weighty = 1;

        // Agrega un panel transparente en la parte superior si es necesario para empujar los elementos hacia abajo
        if (nombresBotones.length < 3) {
            panel.add(new JPanel(), gbc);  // Panel transparente para el espaciado superior
        }

        // Crea un botón para cada nombre en el arreglo y lo añade al panel con restricciones
        for (String nombreBoton : nombresBotones) {
            JButton boton = new JButton(nombreBoton);
            panel.add(boton, gbc);
        }

        // Agrega un panel transparente en la parte inferior para empujar los elementos hacia arriba
        if (nombresBotones.length < 3) {
            panel.add(new JPanel(), gbc);  // Panel transparente para el espaciado inferior
        }

        // Quita cualquier configuración de layout previa y añade el panel
        getContentPane().removeAll();
        setLayout(new GridBagLayout()); // Usa GridBagLayout para el content pane
        add(panel, gbc); // Añade el panel al JFrame con las restricciones
        validate(); // Valida el árbol de componentes
        pack(); // Ajusta el tamaño del frame para acomodar los componentes
        setLocationRelativeTo(null); // Centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String[] nombres = {"Botón 1", "Botón 2", "Botón 3"};
                new Menu_Botones_Generico(nombres).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
