/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Font;

/**
 *
 * @author 34611
 */
public class Menu_Comedor extends javax.swing.JPanel {
    
    private Ventana padre;

    /**
     * Creates new form Menu_Comedor
     */
    public Menu_Comedor(Ventana p) {
        initComponents();
        padre = p;
        
        // Ajustamos el texto al tamaño de ventana
        int ancho_menu = padre.getWidth();
        System.out.println(ancho_menu);
        Font fuente_botones = MenuAydanamar.getFont().deriveFont((float) ancho_menu/15);
        Font fuente_titulo = jLabel1.getFont().deriveFont((float) ancho_menu/13);
        MenuAydanamar.setFont(fuente_botones);
        MenuParaLLevar.setFont(fuente_botones);
        jLabel1.setFont(fuente_titulo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuAydanamar = new javax.swing.JButton();
        MenuParaLLevar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú Comedores");

        MenuAydanamar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MenuAydanamar.setText("Menú Aydanamar");
        MenuAydanamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAydanamarActionPerformed(evt);
            }
        });

        MenuParaLLevar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MenuParaLLevar.setText("Menú para llevar");
        MenuParaLLevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuParaLLevarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuAydanamar, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(MenuParaLLevar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuAydanamar, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuParaLLevar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAydanamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAydanamarActionPerformed
        padre.botonMenuAydanamarPulsado();
    }//GEN-LAST:event_MenuAydanamarActionPerformed

    private void MenuParaLLevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuParaLLevarActionPerformed
        padre.botonMenuParaLlevarPulsado();
    }//GEN-LAST:event_MenuParaLLevarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuAydanamar;
    private javax.swing.JButton MenuParaLLevar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
