/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.DefaultComboBoxModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Seleccion_Clases extends javax.swing.JPanel {

    private Ventana padre;
    
    public Seleccion_Clases(Ventana p) {
        initComponents();
        cambiaOpciones();
        padre = p;
        //Hace falta limitar los valores que toman los combox
        //Usar el método setModel(<cadena strings>)
    }
    
    // Método para manejar swipe up
    public void swipeUp() {
        cambiarIndiceCombox(ComBox1, -1);
        // Agrega aquí el cambio de ComBox2 y ComBox3 si es necesario
    }

    // Método para manejar swipe down
    public void swipeDown() {
        cambiarIndiceCombox(ComBox1, 1);
        // Agrega aquí el cambio de ComBox2 y ComBox3 si es necesario
    }

    // Método para cambiar el índice del JComboBox
    private void cambiarIndiceCombox(javax.swing.JComboBox<String> combox, int delta) {
        int index = combox.getSelectedIndex();
        int nuevoIndice = (index + delta + combox.getItemCount()) % combox.getItemCount();
        combox.setSelectedIndex(nuevoIndice);
    }
    
    private void cambioComboxRueda(javax.swing.JComboBox<String> combox, 
                                   java.awt.event.MouseWheelEvent evt){
        int index = combox.getSelectedIndex();
        int delta = evt.getWheelRotation();

        // Ajusta el índice seleccionado según el desplazamiento de la rueda del ratón
        index = (index - delta + combox.getItemCount()) % combox.getItemCount();
        
        combox.setSelectedIndex(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComBox1 = new javax.swing.JComboBox<>();
        ComBox2 = new javax.swing.JComboBox<>();
        ComBox3 = new javax.swing.JComboBox<>();
        titulo = new javax.swing.JLabel();

        ComBox1.setModel(new javax.swing.DefaultComboBoxModel<>());
        ComBox1.setToolTipText("");
        ComBox1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ComBox1MouseWheelMoved(evt);
            }
        });
        
        
        ComBox2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ComBox2MouseWheelMoved(evt);
            }
        });
        
        

        ComBox3.setModel(new javax.swing.DefaultComboBoxModel<>());
        ComBox3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ComBox3MouseWheelMoved(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titulo.setText("Seleccion Clases");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(titulo)
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(ComBox2)
                    .addComponent(ComBox3))
                .addContainerGap(348, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cambiaOpciones() {
    	ComBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
    	// Cambia los mostrado en el tercer selector en fucnión de los escogido en el segundo y el primero
        ComBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultComboBoxModel<String> model3 = (DefaultComboBoxModel<String>) ComBox3.getModel();
                model3.removeAllElements();

                String sel1 = (String) ComBox2.getSelectedItem();
                String sel2 = (String) ComBox1.getSelectedItem();
                
                // Muy importante este if, por si se cambia el contenido del primer selector después de tener los demás
                if(sel2 != null) {
	                // Si se ha seleecionado clase
	                if (sel1.equals("Clase")){
	                	String[] elems;
	
	                	// Si es planta -1, A o B
	                    if(sel2.equals("-1") || sel2.equals("A") || sel2.equals("B")) {
	                    	elems = new String[]{"", "1", "2"};
	                    }
	                    else {	// Si es planta 0, 1, 2 o 3
	                    	elems = new String[]{"", "1", "2", "3", "4", "5", "6", "7", "8"};
	                    }
	                    
	                    for (String e : elems) {
	                        model3.addElement(e);
	                    }
	                } 
	                else if (sel1.equals("Despacho")){	//Si se ha seleccionado despacho 
	                	model3.addElement("");
	                	
	                	// Si la planta el la 5
	                    if(sel2.equals("5")){
	                    	model3.addElement("1");
	                    }
	                    else{	// Si la planta es la 2, 3 o 4
	                    	for(int i=1; i<41; ++i) {
	                    		model3.addElement(String.valueOf(i));
	                    	}
	                    }
	                }
                }
            }
        });
        
        ComBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Clase", "Despacho" }));
        // Cambia los mostrado en el segundo selector en fucnión de los escogido en el primero
        ComBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultComboBoxModel<String> model1 = (DefaultComboBoxModel<String>) ComBox1.getModel();
                model1.removeAllElements();

                String sel = (String) ComBox2.getSelectedItem();

                if (sel.equals("Clase")){
                    String[] elems = new String[]{"", "-1", "0", "1", "2", "3", "A", "B"};

                    for (String e : elems) {
                        model1.addElement(e);
                    }
                } 
                else if (sel.equals("Despacho")){
                    String[] elems = new String[]{"", "2", "3", "4", "5"};

                    for (String e : elems) {
                        model1.addElement(e);
                    }
                }
            }
        });
        
        ComBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""}));
    }
    
    private void ComBox2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ComBox2MouseWheelMoved
        cambioComboxRueda(ComBox2, evt);
    }//GEN-LAST:event_ComBox2MouseWheelMoved

    private void ComBox1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ComBox1MouseWheelMoved
        cambioComboxRueda(ComBox1, evt);
    }//GEN-LAST:event_ComBox1MouseWheelMoved

    private void ComBox3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ComBox3MouseWheelMoved
        cambioComboxRueda(ComBox3, evt);
    }//GEN-LAST:event_ComBox3MouseWheelMoved

    public String destino() {
    	String sel1 = (String) ComBox2.getSelectedItem();
    	String sel2 = (String) ComBox1.getSelectedItem();
    	String sel3 = (String) ComBox3.getSelectedItem();
    	
    	if(sel1.equals("Clase")) {
    		return sel2 + "." + sel3;
    	}
    	else{
    		return "D" + sel2 + "." + sel3;
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBox1;
    private javax.swing.JComboBox<String> ComBox2;
    private javax.swing.JComboBox<String> ComBox3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
