/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Seleccion_Clases extends javax.swing.JPanel {

    private Ventana padre;
    
    public Seleccion_Clases(Ventana p) {
        initComponents();
        padre = p;
        //Hace falta limitar los valores que toman los combox
        //Usar el método setModel(<cadena strings>)
    }
    
    // Método para manejar swipe up
    public void swipeUp() {
        cambiarIndiceCombox(ComBox1, -1);
        // Agrega aquí el cambio de ComBox2 y ComBox3 si es necesario
    }

    // Método para manejar swipe down
    public void swipeDown() {
        cambiarIndiceCombox(ComBox1, 1);
        // Agrega aquí el cambio de ComBox2 y ComBox3 si es necesario
    }

    // Método para cambiar el índice del JComboBox
    private void cambiarIndiceCombox(javax.swing.JComboBox<String> combox, int delta) {
        int index = combox.getSelectedIndex();
        int nuevoIndice = (index + delta + combox.getItemCount()) % combox.getItemCount();
        combox.setSelectedIndex(nuevoIndice);
    }
    
    private void cambioComboxRueda(javax.swing.JComboBox<String> combox, 
                                   java.awt.event.MouseWheelEvent evt){
        int index = combox.getSelectedIndex();
        int delta = evt.getWheelRotation();

        // Ajusta el índice seleccionado según el desplazamiento de la rueda del ratón
        index = (index - delta + combox.getItemCount()) % combox.getItemCount();
        
        combox.setSelectedIndex(index);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComBox1 = new javax.swing.JComboBox<>();
        ComBox2 = new javax.swing.JComboBox<>();
        ComBox3 = new javax.swing.JComboBox<>();
        titulo = new javax.swing.JLabel();
        boton_si = new javax.swing.JButton();
        boton_no = new javax.swing.JButton();

        ComBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-1", "0", "1", "2", "3", "4", "5" }));
        ComBox1.setToolTipText("");
        ComBox1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ComBox1MouseWheelMoved(evt);
            }
        });

        ComBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clase", "Despacho" }));
        ComBox2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ComBox2MouseWheelMoved(evt);
            }
        });

        ComBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        ComBox3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                ComBox3MouseWheelMoved(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        titulo.setText("Seleccion Clases");

        boton_si.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        boton_si.setText("Sí");
        boton_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_siActionPerformed(evt);
            }
        });

        boton_no.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        boton_no.setText("No");
        boton_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(boton_no, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_si, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(titulo)
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(ComBox2)
                    .addComponent(ComBox3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_si, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_no, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComBox2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ComBox2MouseWheelMoved
        cambioComboxRueda(ComBox2, evt);
    }//GEN-LAST:event_ComBox2MouseWheelMoved

    private void ComBox1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ComBox1MouseWheelMoved
        cambioComboxRueda(ComBox1, evt);
    }//GEN-LAST:event_ComBox1MouseWheelMoved

    private void ComBox3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_ComBox3MouseWheelMoved
        cambioComboxRueda(ComBox3, evt);
    }//GEN-LAST:event_ComBox3MouseWheelMoved

    private void boton_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_siActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_boton_siActionPerformed

    private void boton_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_noActionPerformed
        padre.anterior();
    }//GEN-LAST:event_boton_noActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBox1;
    private javax.swing.JComboBox<String> ComBox2;
    private javax.swing.JComboBox<String> ComBox3;
    private javax.swing.JButton boton_no;
    private javax.swing.JButton boton_si;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
