/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author 34611
 */
public class Seleccion_Tipo_Menu extends javax.swing.JPanel {

    private Ventana padre;
    
    /**
     * Creates new form Seleccion_Tipo_Menu
     */
    public Seleccion_Tipo_Menu(Ventana p) {
        initComponents();
        padre = p;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Almuerzo = new javax.swing.JButton();
        Cena = new javax.swing.JButton();
        Ovolacteoveg = new javax.swing.JButton();
        Vegano = new javax.swing.JButton();
        Celiaco = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("¿Qué menú desea?");

        Almuerzo.setBackground(new java.awt.Color(255, 255, 255));
        Almuerzo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Almuerzo.setText("Almuerzo");
        Almuerzo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 4, true));
        Almuerzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmuerzoActionPerformed(evt);
            }
        });

        Cena.setBackground(new java.awt.Color(255, 255, 255));
        Cena.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Cena.setText("Cena");
        Cena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 4, true));
        Cena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CenaActionPerformed(evt);
            }
        });

        Ovolacteoveg.setBackground(new java.awt.Color(255, 255, 255));
        Ovolacteoveg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Ovolacteoveg.setText("Ovolacteovegetariano");
        Ovolacteoveg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 4, true));
        Ovolacteoveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OvolacteovegActionPerformed(evt);
            }
        });

        Vegano.setBackground(new java.awt.Color(255, 255, 255));
        Vegano.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Vegano.setText("Vegano");
        Vegano.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 4, true));
        Vegano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeganoActionPerformed(evt);
            }
        });

        Celiaco.setBackground(new java.awt.Color(255, 255, 255));
        Celiaco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Celiaco.setText("T-Celiaco");
        Celiaco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 4, true));
        Celiaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeliacoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Celiaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Vegano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Ovolacteoveg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Almuerzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(Almuerzo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(Cena, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Ovolacteoveg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Vegano, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Celiaco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AlmuerzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmuerzoActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_AlmuerzoActionPerformed

    private void CenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CenaActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_CenaActionPerformed

    private void OvolacteovegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OvolacteovegActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_OvolacteovegActionPerformed

    private void VeganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeganoActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_VeganoActionPerformed

    private void CeliacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeliacoActionPerformed
        padre.siguiente();
    }//GEN-LAST:event_CeliacoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Almuerzo;
    private javax.swing.JButton Celiaco;
    private javax.swing.JButton Cena;
    private javax.swing.JButton Ovolacteoveg;
    private javax.swing.JButton Vegano;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
