/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQL;

import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author 34667
 */
public class ConexionSQL extends javax.swing.JFrame {
    
    // Atributo global
    String nombreBaseDatos = "Comedor";
    String nombreBaseDatos2 = "Localizaciones";

    /**
     * Creates new form ConexionSQL
     */
    public ConexionSQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConectar = new javax.swing.JButton();
        btnBBDDComedor = new javax.swing.JButton();
        btnBBDDLocalizaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConectar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        btnBBDDComedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBBDDComedor.setText("Crear BBDD Comedor");
        btnBBDDComedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBDDComedorActionPerformed(evt);
            }
        });

        btnBBDDLocalizaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBBDDLocalizaciones.setText("Crear BBDD Localizaciones");
        btnBBDDLocalizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBDDLocalizacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnBBDDComedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnBBDDLocalizaciones)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBBDDComedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBBDDLocalizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        
        String bases = "";
        
        try{
            Statement sql = Conexion.getConexion("master").createStatement();
            
            String consulta = "SELECT name FROM master.dbo.sysdatabases";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += resultado.getString(1) + "\n";
            }
            
            JOptionPane.showMessageDialog(null, bases);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnBBDDComedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBDDComedorActionPerformed

        try{
            Statement sql = Conexion.getConexion("master").createStatement();
            
            // Crear la nueva base de datos
            String comando = "CREATE DATABASE " + nombreBaseDatos;
            sql.executeUpdate(comando);

            System.out.println("Base de datos '" + nombreBaseDatos + "' creada correctamente.");
            
            // Crear la tabla de menús
            sql = Conexion.getConexion(nombreBaseDatos).createStatement();
            
            String cmd = "CREATE TABLE Menus (" +
                    "Dia NVARCHAR(40)," + // Puedes ajustar la longitud según necesites
                    "TipoMenu NVARCHAR(255)," +
                    "Primero NVARCHAR(255)," +
                    "Segundo NVARCHAR(255)," +
                    "Acompanamiento NVARCHAR(255)," +
                    "Postre NVARCHAR(255)," +
                    "PRIMARY KEY (Dia, TipoMenu)" + // Clave primaria compuesta
                    ")";
            sql.executeUpdate(cmd);

            System.out.println("Tabla 'Menus' creada correctamente.");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnBBDDComedorActionPerformed

    private void btnBBDDLocalizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBDDLocalizacionesActionPerformed
        try{
            Statement sql = Conexion.getConexion("master").createStatement();
            
            // Crear la nueva base de datos
            String comando = "CREATE DATABASE " + nombreBaseDatos2;
            sql.executeUpdate(comando);

            System.out.println("Base de datos '" + nombreBaseDatos2 + "' creada correctamente.");
            
            // Crear la tabla de ubicaciones
            sql = Conexion.getConexion(nombreBaseDatos2).createStatement();
            
            String cmd = "CREATE TABLE Imagenes (" +
                    "Ubicacion NVARCHAR(40)," + // Puedes ajustar la longitud según necesites
                    "Imagen VARBINARY(MAX)," +
                    "Descripcion NVARCHAR(255)," +
                    "PRIMARY KEY (Ubicacion)" + 
                    ")";
            sql.executeUpdate(cmd);

            System.out.println("Tabla 'Imagenes' creada correctamente.");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnBBDDLocalizacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConexionSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConexionSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConexionSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConexionSQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConexionSQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBBDDComedor;
    private javax.swing.JButton btnBBDDLocalizaciones;
    private javax.swing.JButton btnConectar;
    // End of variables declaration//GEN-END:variables
}
